{"name": "test_login_user_correct", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://automationexercise.com/\", waiting until \"load\"", "trace": "page = <Page url='https://automationexercise.com/'>\ntest_user = {'email': 'tymur_8ee75b@example.com', 'name': 'TymurTest', 'password': 'TestPass123'}\n\n    @pytest.fixture(scope=\"function\")\n    def ensure_registered_user(page, test_user):\n>       page.goto(\"https://automationexercise.com\")\n\nconftest.py:46: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nC:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:9002: in goto\n    self._sync(\nC:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_page.py:556: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nC:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_frame.py:146: in goto\n    await self._channel.send(\nC:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py:69: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x000001F07911B110>\ncb = <function Channel.send.<locals>.<lambda> at 0x000001F079061620>\nis_internal = False, title = None\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False, title: str = None\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(\n            task, \"__pw_stack__\", None\n        ) or inspect.stack(0)\n    \n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal, title)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nE           Call log:\nE             - navigating to \"https://automationexercise.com/\", waiting until \"load\"\n\nC:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_connection.py:558: TimeoutError"}, "start": 1752419342736, "stop": 1752419342736, "uuid": "306bdde1-23be-4735-ba2e-74a089ca5cb4", "historyId": "af101ee99385e6cbf6385c639b6a8b0e", "testCaseId": "af101ee99385e6cbf6385c639b6a8b0e", "fullName": "tests.test_auth_flow#test_login_user_correct", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_flow"}, {"name": "host", "value": "DESKTOP-BTCJ9P6"}, {"name": "thread", "value": "6656-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_flow"}]}